name: b11-workflow

on:
  push:

jobs:
  run-additio:
    runs-on: [self-hosted, linux]

    steps:
      - name: Create a new file
        run: |
          echo "test" > report.txt
          cat report.txt